---
services: docker

env:
  - distro: centos7
  - distro: ubuntu1604
  - distro: debian9

script:
  # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)
  - export cleanup=false

  # Download test shim.
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/geerlingguy/73ef1e5ee45d8694570f334be385e181/raw/
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - ${PWD}/tests/test.sh

  # Test if exim is working.
  # - 'docker exec --tty ${container_id} env TERM=xterm exim -bV'

  # # Make sure GitLab is running.
  # - >
  #   curl --insecure -s -o /dev/null -w "%{http_code}" https://localhost/users/password/new
  #   | grep -q '200'
  #   && (echo 'Status code 200 test: pass' && exit 0)
  #   || (echo 'Status code 200 test: fail' && exit 1)

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
