---
- name: Check if Git is configured.
  shell: >
    sudo -u git -H git config --list
    chdir=/home/git
  register: git_config
  changed_when: false

- name: Configure Git globals for GitLab.
  shell: >
    sudo -u git -H git config --global {{ item.key }} {{ item.value }}
    chdir=/home/git/gitlab
  with_items:
  - { key: user.name, value: "GitLab" }
  - { key: user.email, value: "gitlab@{{ hostname }}" }
  - { key: core.autocrlf, value: "input" }
  when: "'user.email=gitlab@{{ hostname }}' not in git_config.stdout"
