---
- name: Install development tools.
  yum: name='@development' state=installed

- name: Install required dependencies.
  yum: name={{ item }} state=installed enablerepo=epel
  with_items:
  - vim-enhanced
  - readline
  - readline-devel
  - ncurses-devel
  - gdbm-devel
  - glibc-devel
  - tcl-devel
  - openssl-devel
  - curl-devel
  - expat-devel
  - db4-devel
  - byacc
  - sqlite-devel
  - gcc-c++
  - libyaml
  - libyaml-devel
  - libffi
  - libffi-devel
  - libxml2
  - libxml2-devel
  - libxslt
  - libxslt-devel
  - libicu
  - libicu-devel
  - system-config-firewall-tui
  - python-devel
  - python-docutils
  - sudo
  - wget
  - crontabs
  - logwatch
  - logrotate
  - perl-Time-HiRes
