---
- name: Create self-signed certificate.
  command: >
    openssl req -new -nodes -x509 -subj "/C=US/ST=Missouri/L=Saint Louis/O=IT/CN={{ hostname }}" -days 3650 -keyout /etc/nginx/gitlab.key -out /etc/nginx/gitlab.crt -extensions v3_ca
    creates=/etc/nginx/gitlab.crt

- name: Add nginx user to git group.
  user: >
    name=nginx
    group=nginx
    groups=git

- name: Copy nginx configuration.
  template: src=nginx_gitlab.conf.j2 dest=/etc/nginx/conf.d/gitlab.conf owner=root group=root mode=644
  notify: restart nginx
